# Generated by Django 3.2.5 on 2021-08-26 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_safe_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=255)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website_username', models.CharField(max_length=50)),
                ('website_password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.DeleteModel(
            name='PasswordMaster',
        ),
    ]
