# Generated by Django 3.2.5 on 2021-08-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe_api', '0002_auto_20210826_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordmaster',
            old_name='user',
            new_name='created_by',
        ),
    ]
